apiVersion: apps/v1
kind: Deployment
metadata:
  name: datavault-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: datavault-backend
          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
