apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: datavault

patches:
  - path: deployment-patch.yaml

images:
  - name: registry.gitlab.com/yourorg/datavault-pro/backend
    newTag: "2.3.0"
